apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-secure-prom-exp-scanning-cm
  namespace: sysdig-prom-exp
data:
  SECURE_URL: "https://secure.sysdig.com"
  SCHEDULED_RUN_MINUTES: "720"  # Queries sysdig secure api at this interval.
  PROM_EXP_URL_PORT: "8000" # pod is listening on this port
  BATCH_LIMIT: "100" # Max records to be queried in a single request.
  CUSTOMER_NAME: "Sysdig"
  QUERY_FEATURES_LIST: "all" # list - all - fetches all features(scanning, compliance, etc) or scanning_v1, scanning_v2, compliance or benchmark